version: '3.7'
volumes:
  postgres-data:
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=aspire
      - POSTGRES_USER=aspire
      - POSTGRES_PASSWORD=aspire
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: aspire-db-cont